import { sql } from 'drizzle-orm';
import {
  check,
  index,
  integer,
  primaryKey,
  sqliteTable,
  text,
  uniqueIndex,
} from 'drizzle-orm/sqlite-core';

/**
 * Drizzle schema. The SQL that actually creates these tables lives in
 * `migrations.ts` (hand written, because FTS5 virtual tables and triggers cannot be
 * generated by drizzle-kit). Keep the two in sync; `schema.test.ts` checks that.
 */

export const packs = sqliteTable(
  'packs',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    name: text('name').notNull(),
    category: text('category').notNull(),
    sourceUrl: text('source_url'),
    version: text('version').notNull().default('1'),
    pinnedDefault: integer('pinned_default', { mode: 'boolean' }).notNull().default(false),
    installedAt: integer('installed_at').notNull(),
  },
  (t) => [uniqueIndex('packs_name_unique').on(t.name)],
);

export const items = sqliteTable(
  'items',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    title: text('title').notNull(),
    body: text('body').notNull(),
    description: text('description').notNull().default(''),
    type: text('type', { enum: ['snippet', 'command', 'checklist'] })
      .notNull()
      .default('snippet'),
    language: text('language'),
    source: text('source', { enum: ['user', 'builtin', 'tldr', 'url'] })
      .notNull()
      .default('user'),
    packId: integer('pack_id').references(() => packs.id, { onDelete: 'set null' }),
    pinned: integer('pinned', { mode: 'boolean' }).notNull().default(false),
    useCount: integer('use_count').notNull().default(0),
    lastUsedAt: integer('last_used_at'),
    createdAt: integer('created_at').notNull(),
    updatedAt: integer('updated_at').notNull(),
  },
  (t) => [
    index('items_pack_idx').on(t.packId),
    index('items_pinned_idx').on(t.pinned),
    index('items_use_count_idx').on(t.useCount),
    check('items_type_check', sql`${t.type} in ('snippet','command','checklist')`),
    check('items_source_check', sql`${t.source} in ('user','builtin','tldr','url')`),
  ],
);

export const tags = sqliteTable(
  'tags',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    name: text('name').notNull(),
  },
  (t) => [uniqueIndex('tags_name_unique').on(t.name)],
);

export const itemTags = sqliteTable(
  'item_tags',
  {
    itemId: integer('item_id')
      .notNull()
      .references(() => items.id, { onDelete: 'cascade' }),
    tagId: integer('tag_id')
      .notNull()
      .references(() => tags.id, { onDelete: 'cascade' }),
  },
  (t) => [primaryKey({ columns: [t.itemId, t.tagId] }), index('item_tags_tag_idx').on(t.tagId)],
);

export const collections = sqliteTable('collections', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name').notNull(),
  createdAt: integer('created_at').notNull(),
});

export const collectionItems = sqliteTable(
  'collection_items',
  {
    collectionId: integer('collection_id')
      .notNull()
      .references(() => collections.id, { onDelete: 'cascade' }),
    itemId: integer('item_id')
      .notNull()
      .references(() => items.id, { onDelete: 'cascade' }),
    addedAt: integer('added_at').notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.collectionId, t.itemId] }),
    index('collection_items_item_idx').on(t.itemId),
  ],
);

/** Small key/value table for app settings (theme, font size). */
export const settings = sqliteTable('settings', {
  key: text('key').primaryKey(),
  value: text('value').notNull(),
});

export type ItemRow = typeof items.$inferSelect;

export const schema = { packs, items, tags, itemTags, collections, collectionItems, settings };
